[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.8.0"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.5.1"
